runtime_error: 0.1
sub_runtime_error: 0.02
search_radius: 12.0
threshold: 0.40
search_interval: 2.0

start_position: [0, 1, 2.0]
end_position: [20.0, 0.0, 4.0]
local_map_size_xyz: [10.0, 10.0, 10.0]
height: [1.0, 4.0]